services:
  - type: web
    name: synapse-backend
    env: node
    plan: free
    rootDir: synapse_os/server
    buildCommand: bash render-build.sh
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: APIFY_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: VIDEO_GENERATOR_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: VIDEO_GENERATOR_EMAIL
        sync: false
      - key: VIDEO_GENERATOR_PASSWORD
        sync: false
